# 程序端口号 springboot 建议使用yml文件
server:
  port: 7900
spring:
  application:
    name: user # 应用名称也就是别名
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka/ # curl 风格